# Generated by Django 6.0.7 on 2026-07-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('outlook', 'Outlook'), ('others', 'Others')], default='others', max_length=20)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('headers', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
