# Generated by Django 6.0.7 on 2026-07-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooklog',
            name='source',
            field=models.CharField(choices=[('meta', 'Meta'), ('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('outlook', 'Outlook'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_business_id', models.CharField(blank=True, max_length=255, null=True)),
                ('waba_id', models.CharField(max_length=255)),
                ('phone_number_id', models.CharField(max_length=255)),
                ('display_phone_number', models.CharField(max_length=50)),
                ('access_token', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quality_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('messaging_limit_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number_id'], name='core_whatsa_phone_n_392164_idx')],
            },
        ),
    ]
