# Generated by Django 6.0.7 on 2026-07-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_webhooklog_source_whatsappaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappaccount',
            old_name='access_token',
            new_name='token_data',
        ),
    ]
