# Generated by Django 6.0.7 on 2026-07-22 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_access_token_whatsappaccount_token_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_mail', models.EmailField(max_length=254, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('tenant_id', models.CharField(max_length=255)),
                ('secret_id', models.CharField(blank=True, max_length=255, null=True)),
                ('api_endpoint', models.URLField(default='https://graph.microsoft.com/v1.0')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutlookAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('grant_type', models.CharField(default='client_credentials', max_length=50)),
                ('token_type', models.CharField(blank=True, max_length=50, null=True)),
                ('expires_in', models.PositiveIntegerField(default=0)),
                ('ext_expires_in', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='core.outlookaccount')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_url', models.URLField()),
                ('resource', models.CharField(default='', max_length=255)),
                ('change_type', models.CharField(default='created', max_length=50)),
                ('client_state', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.outlookaccount')),
            ],
        ),
    ]
