# Generated by Django 6.0.7 on 2026-07-20 11:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('meta', 'Meta'), ('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('outlook', 'Outlook'), ('others', 'Others')], default='others', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number'], name='lead_lead_phone_n_eb14eb_idx'), models.Index(fields=['source', 'phone_number'], name='lead_lead_source_27fe3b_idx')],
                'unique_together': {('source', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(blank=True, max_length=500, null=True)),
                ('send_by', models.CharField(choices=[('AI', 'Ai'), ('AGENT', 'Agent'), ('CLIENT', 'Client')], default='AI', max_length=50)),
                ('direction', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=20)),
                ('message_type', models.CharField(choices=[('Text', 'Text'), ('Image', 'Image'), ('Audio', 'Audio'), ('Video', 'Video'), ('File', 'File')], default='Text', max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='messages/')),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Received', 'Received'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Failed', 'Failed')], default='Sent', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lead.lead')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='media/')),
                ('meta_media_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='lead.message')),
            ],
        ),
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['system_id'], name='lead_messag_system__372c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['lead'], name='lead_messag_lead_id_ed91d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadtag',
            unique_together={('lead', 'tag')},
        ),
    ]
