# Generated by Django 6.0.7 on 2026-07-23 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_email_alter_lead_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='lead_messag_system__372c6c_idx',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='system_id',
            new_name='conversation_message_id',
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='meta_media_id',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='download_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='provider_media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='internet_message_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='raw_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__isnull', False)), fields=('source', 'phone_number'), name='unique_phone_source'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('source', 'email'), name='unique_email_source'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='lead.lead'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.conversation'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['provider_message_id'], name='lead_messag_provide_7e8e44_idx'),
        ),
    ]
